### ISSUE TITLE
ScriptEngine: debug symbols do not load when using Doorstop 4

### ISSUE THREAD

**Issue by aldelaro5** [BepInEx/BepInEx.Debug#13]
I am trying to combine the hot reloading capability of ScriptEngine with the debugging stuff of Doorstop 4. I made a fork of bepinex that uses Doorstop 4 to do that and if I do not use ScriptEngine (so I put my dll and pdb in the plugins folder), everything works with debugging.

However, as soon as I start to use ScriptEngine, hot realoading works, but I can no longer debug which to me limit greatly the use of it (since I often need debugging more than hot reloading).

I attempted to look into it myself because it seemed that there is some options to load symbols when loading the assembly in the fashion ScriptEngine does it, but I wasn't successful. I really wonder why it just can't pickup the pdb since it is loading the assembly which should cause the psb to get picked up.

FYI, this is the bepinex fork I am using: https://github.com/aldelaro5/BepInEx/tree/v5-lts

**Comment by ManlyMarco** [comment]
Not sure why you needed to make a fork to debug instead of using simpler means, but it shouldn't make a difference, you just need to find the right in-memory module to drop breakpoints in after the assembly is reloaded. It's easiest to drop a breakpoint in some outside method that the reloaded assembly calls and walk back the stack trace.

**Comment by aldelaro5** [comment]
> Not sure why you needed to make a fork to debug instead of using simpler means, but it shouldn't make a difference, you just need to find the right in-memory module to drop breakpoints in after the assembly is reloaded. It's easiest to drop a breakpoint in some outside method that the reloaded assembly calls and walk back the stack trace.

I am not sure what you mean here: I just put breakpoints on the plugin's sources after attaching my IDE to doorstop's which ultimately loads an assembly with the same sources so wouldn't I in theory already have everything needed? Cause afaik, this apparently isn't enough while it is if I don't use scriptEngine and use a regular plugin which I load the normal way; every breakpoints gets hit here, but they don't resolve when I use scriptEngine.

Sidenote: it happens to be the simplest way to debug in my case because the same method allows me to debug plugins AND recompiled game sources (which don't need any treatment after decompilation to be recompiled). Dnspyex isn't cutting it because not only it only works on Windows, it's also giving terrible decompilation on the game assmeblies on top of being incredebly slow to decompile during debugging on some key methods with game logic (we talking minutes of waiting because these methods are huge in volume). 

The only alternative, turning the build into a dev build, is not only messy because it requires me to replace a lot of files, it's also not doing much more than what doorstop 4 could already do. The only use I found is it allows me to use the unity's profiler while doorstop 4 doesn't support this, but I don't need it too much.

**Comment by ManlyMarco** [comment]
I don't know if it's possible to target an in-memory module with VS debugger so can't help much. In DnSpy you can go to the modules view and look for the most recently loaded one or do the stack trace trick I mentioned. Breakpoints placed inside the on-disk assembly file will not work because the assembly is modified in-memory (name change, so the link to the assembly on disk is broken) to allow it to be loaded multiple times for the hot reload to work (this is necessary because you can't unload assemblies and can't load assemblies that have the same assembly name as an already loaded one).
